---
 - name: Tomacat configuration
   hosts: localhost
   user: shifamariam12
   sudo: yes
   tasks:
    - name: Install Prerequisites.
      apt: pkg={{ item }} state=latest
      with_items:
        - curl
        - zip
        - unzip
   roles:
        #- java
        - tomcat
